Roby = {}

Roby.WeaponDamage = {
    Multipliers = {
        WEAPON_UNARMED = 0.3, 
        WEAPON_KNIFE = 0.5,
        WEAPON_BAT = 0.5,
        WEAPON_CROWBAR = 0.35,
        WEAPON_NIGHTSTICK = 0.2,
        WEAPON_FLASHLIGHT = 0.1, 
        WEAPON_HAMMER = 0.35,
        WEAPON_GOLFCLUB = 0.35,
        WEAPON_BOTTLE = 0.5,
        WEAPON_DAGGER = 0.5,
        WEAPON_HATCHET = 1.0,
        WEAPON_KNUCKLE = 0.45,
        WEAPON_MACHETE = 0.45,
        WEAPON_SWITCHBLADE = 0.5,
        WEAPON_BATTLEAXE = 0.45,
        WEAPON_POOLCUE = 0.35,
        WEAPON_WRENCH = 0.45,
        WEAPON_STUNGUN = 0.0,

        WEAPON_PISTOL = 0.7,
        WEAPON_COMBATPISTOL = 0.7,
        WEAPON_APPISTOL = 0.5,
        WEAPON_PISTOL50 = 0.75,

        WEAPON_MICROSMG = 0.6,
        WEAPON_SMG = 0.75,
        WEAPON_ASSAULTSMG = 0.75,

        WEAPON_ASSAULTRIFLE = 0.75,
        WEAPON_CARBINERIFLE = 0.75,
        WEAPON_ADVANCEDRIFLE = 0.75,

        WEAPON_PUMPSHOTGUN = 0.68,
        WEAPON_SAWNOFFSHOTGUN = 0.68,
        WEAPON_ASSAULTSHOTGUN = 0.68,

        WEAPON_SNIPERRIFLE = 1.0,
        WEAPON_HEAVYSNIPER = 1.0,
    },
    HeadshotOneShot = true,
    HeadBones = {
        [31086] = true, 
        [39317] = true, 
        [5956]  = true, 
        [17188] = true, 
        [4137]  = true, 
        [12844] = true, 
        [27474] = true, 
        [20178] = true, 
        [11174] = true, 
        [17719] = true, 
        [20279] = true, 
        [46078] = true, 
    },
    BlockedHeadshotWeapons = {
        WEAPON_UNARMED = true,
        WEAPON_KNIFE = true,
        WEAPON_BAT = true,
        WEAPON_CROWBAR = true,
        WEAPON_NIGHTSTICK = true,
        WEAPON_FLASHLIGHT = true,
        WEAPON_HAMMER = true,
        WEAPON_GOLFCLUB = true,
        WEAPON_BOTTLE = true,
        WEAPON_DAGGER = true,
        WEAPON_HATCHET = true,
        WEAPON_KNUCKLE = true,
        WEAPON_MACHETE = true,
        WEAPON_SWITCHBLADE = true,
        WEAPON_BATTLEAXE = true,
        WEAPON_POOLCUE = true,
        WEAPON_WRENCH = true,
        WEAPON_STUNGUN = true,
    }
}
